<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>TinyBlueWhale.EngineQuery.Core</PackageId>
    <Description>Core strongly typed SQL query builder and metadata system for EngineQuery.</Description>
    <PackageTags>dotnet;sql;query-builder;dapper;cqrs;fluent-api;enginequery</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TinyBlueWhale.EngineQuery.Abstractions\TinyBlueWhale.EngineQuery.Abstractions.csproj" />
    <ProjectReference Include="..\TinyBlueWhale.EngineQuery.Metadata\TinyBlueWhale.EngineQuery.Metadata.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>