<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>TinyBlueWhale.EngineQuery.Metadata</PackageId>
    <Description>Metadata abstractions and resolvers for EngineQuery SQL generation.</Description>
    <PackageTags>dotnet;sql;query-builder;metadata;fluent-mapping;attributes;enginequery</PackageTags>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\TinyBlueWhale.EngineQuery.Abstractions\TinyBlueWhale.EngineQuery.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>