<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="NUnit"/>
    <PackageReference Include="NUnit.Analyzers"/>
    <PackageReference Include="NUnit3TestAdapter"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TinyBlueWhale.EngineQuery.Abstractions\TinyBlueWhale.EngineQuery.Abstractions.csproj" />
    <ProjectReference Include="..\TinyBlueWhale.EngineQuery.Metadata.EntityFramework\TinyBlueWhale.EngineQuery.Metadata.EntityFramework.csproj" />
    <ProjectReference Include="..\TinyBlueWhale.EngineQuery.MySql\TinyBlueWhale.EngineQuery.MySql.csproj" />
    <ProjectReference Include="..\TinyBlueWhale.EngineQuery.PostgreSql\TinyBlueWhale.EngineQuery.PostgreSql.csproj" />
    <ProjectReference Include="..\TinyBlueWhale.EngineQuery.SqlServer\TinyBlueWhale.EngineQuery.SqlServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Snapshots\MySql\" />
    <Folder Include="Snapshots\PostgreSql\" />
    <Folder Include="Snapshots\SqlServer\" />
  </ItemGroup>

</Project>
