using TinyBlueWhale.EngineQuery.Abstractions.Enums;
using TinyBlueWhale.EngineQuery.Core.QueryDefinitions;
using TinyBlueWhale.EngineQuery.Sql.Compilation;

namespace TinyBlueWhale.EngineQuery.Sql.Interfaces.Strategies
{
    #region Pagination

    /// <summary>
    /// Defines provider-specific SQL pagination behavior.
    /// </summary>
    public interface IPaginationStrategy
    {
        /// <summary>
        /// Builds the SQL pagination clause for the specified query definition.
        /// </summary>
        /// <param name="queryDefinition">
        /// Query definition containing pagination metadata.
        /// </param>
        /// <param name="context">
        /// Current SQL compilation context.
        /// </param>
        /// <returns>
        /// Provider-specific SQL pagination clause.
        /// </returns>
        string Build(CompiledQueryDefinition queryDefinition, QueryCompilationContext context);
    }

    /// <summary>
    /// Defines a provider profile capable of supplying SQL pagination behavior.
    /// </summary>
    public interface IPaginationStrategyProvider
    {
        /// <summary>
        /// Creates the pagination strategy associated with the provider profile.
        /// </summary>
        /// <returns>
        /// Pagination strategy used to generate provider-specific pagination SQL.
        /// </returns>
        IPaginationStrategy CreatePaginationStrategy();
    }

    #endregion

    #region Cte

    /// <summary>
    /// Defines provider-specific SQL behavior required to build common table expression clauses.
    /// </summary>
    public interface ICTEStrategy
    {
        /// <summary>
        /// Resolves the SQL keyword used when building recursive common table expressions.
        /// </summary>
        /// <returns>
        /// SQL keyword used to start a recursive common table expression clause.
        /// </returns>
        string ResolveRecursiveCteKeyword();
    }

    /// <summary>
    /// Defines a provider profile capable of supplying the common table expression strategy used during SQL compilation.
    /// </summary>
    public interface ICTEStrategyProvider
    {
        /// <summary>
        /// Creates the common table expression strategy associated with the provider profile.
        /// </summary>
        /// <returns>
        /// Common table expression strategy used during SQL compilation.
        /// </returns>
        ICTEStrategy CreateCteStrategy();
    }

    #endregion

    #region Lateral Joins

    /// <summary>
    /// Defines provider-specific SQL rendering behavior for lateral join operations.
    /// </summary>
    public interface ILateralJoinStrategy
    {
        /// <summary>
        /// Gets the SQL join keyword associated with the specified APPLY operation.
        /// </summary>
        /// <param name="applyType">
        /// APPLY operation type.
        /// </param>
        /// <returns>
        /// Provider-specific SQL join keyword.
        /// </returns>
        string GetJoinKeyword(QueryApplyType applyType);

        /// <summary>
        /// Gets the SQL suffix appended after the lateral join expression.
        /// </summary>
        /// <returns>
        /// Provider-specific SQL suffix.
        /// </returns>
        string GetJoinSuffix();
    }

    /// <summary>
    /// Defines a provider capable of supplying the lateral join rendering strategy.
    /// </summary>
    public interface ILateralJoinStrategyProvider
    {
        /// <summary>
        /// Gets the lateral join rendering strategy.
        /// </summary>
        ILateralJoinStrategy CreateLateralJoinStrategy();
    }

    #endregion

    /// <summary>
    /// Defines provider-specific SQL behavior for retrieving an identity value
    /// generated by an INSERT command.
    /// </summary>
    public interface IInsertIdentityRetrievalStrategy
    {
        /// <summary>
        /// Appends provider-specific identity retrieval SQL to the generated INSERT command.
        /// </summary>
        /// <param name="identityDefinition">
        /// Identity retrieval definition associated with the INSERT command.
        /// </param>
        /// <param name="commandText">
        /// Generated INSERT command text.
        /// </param>
        /// <param name="context">
        /// Current SQL compilation context.
        /// </param>
        /// <returns>
        /// INSERT command including provider-specific identity retrieval SQL.
        /// </returns>
        string AppendIdentityRetrieval(QueryInsertIdentityDefinition identityDefinition, string commandText, QueryCompilationContext context);
    }

    /// <summary>
    /// Defines a provider profile capable of supplying the INSERT identity retrieval strategy.
    /// </summary>
    public interface IInsertIdentityRetrievalStrategyProvider
    {
        /// <summary>
        /// Creates the INSERT identity retrieval strategy associated with the provider profile.
        /// </summary>
        /// <returns>
        /// INSERT identity retrieval strategy used during SQL compilation.
        /// </returns>
        IInsertIdentityRetrievalStrategy CreateInsertIdentityRetrievalStrategy();
    }
}
