using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using TinyBlueWhale.EngineQuery.Generators.Models;
using TinyBlueWhale.EngineQuery.Generators.Rendering;

namespace TinyBlueWhale.EngineQuery.Generators.Generation
{
    /// <summary>
    /// Generates dependency injection registrations for discovered EngineQuery
    /// provider profile factories and generated query engines.
    /// </summary>
    internal static class DependencyInjectionGenerator
    {
        private const string GeneratedNamespace =
            "TinyBlueWhale.EngineQuery.Generated";

        /// <summary>
        /// Generates dependency injection registration for all discovered provider profile factories.
        /// </summary>
        internal static void Generate(SourceProductionContext context, GenerationModel model)
        {
            var serviceCollectionExtensions = model.Compilation.GetTypeByMetadataName(
                "TinyBlueWhale.EngineQuery.DependencyInjection.Extensions.ServiceCollectionExtensions");

            if (serviceCollectionExtensions is null)
                return;

            var registerMethod = serviceCollectionExtensions
                .GetMembers("RegisterGeneratedQueryEngineFactories")
                .OfType<IMethodSymbol>()
                .FirstOrDefault(method =>
                    method.IsPartialDefinition &&
                    method.Parameters.Length == 1 &&
                    method.Parameters[0].Type.ToDisplayString() ==
                    "Microsoft.Extensions.DependencyInjection.IServiceCollection");

            if (registerMethod is null)
                return;

            var source = new StringBuilder();

            source.AppendLine("// <auto-generated />");
            source.AppendLine("#nullable enable");
            source.AppendLine();
            source.AppendLine("namespace TinyBlueWhale.EngineQuery.DependencyInjection.Extensions");
            source.AppendLine("{");
            source.AppendLine("    /// <summary>");
            source.AppendLine("    /// Provides generated EngineQuery dependency injection registrations.");
            source.AppendLine("    /// </summary>");
            source.AppendLine("    public static partial class ServiceCollectionExtensions");
            source.AppendLine("    {");
            source.AppendLine("        /// <summary>");
            source.AppendLine("        /// Registers generated strongly typed query engine factories.");
            source.AppendLine("        /// </summary>");
            source.AppendLine("        /// <param name=\"services\">");
            source.AppendLine("        /// Service collection receiving generated query engine factories.");
            source.AppendLine("        /// </param>");
            source.AppendLine("        static partial void RegisterGeneratedQueryEngineFactories(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            source.AppendLine("        {");

            foreach (var profileModel in model.Profiles)
                AppendFactoryRegistration(source, profileModel.Profile);

            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");

            context.AddSource("ServiceCollectionExtensions.QueryEngineFactories.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        }

        /// <summary>
        /// Appends dependency injection registrations associated with a provider profile.
        /// </summary>
        private static void AppendFactoryRegistration(StringBuilder source, INamedTypeSymbol profile)
        {
            var profileType = profile.ToDisplayString(CSharpSourceRenderer.GeneratedTypeDisplayFormat);
            var engineName = CSharpSourceRenderer.GetEngineName(profile);
            var engineInterfaceName = $"global::{GeneratedNamespace}.I{engineName}";
            var engineImplementationName = $"global::{GeneratedNamespace}.{engineName}";
            var factoryInterface = $"global::TinyBlueWhale.EngineQuery.DependencyInjection.Interfaces.IQueryEngineFactory<{profileType}, {engineInterfaceName}>";
            var factoryImplementation = $"global::TinyBlueWhale.EngineQuery.DependencyInjection.Factories.QueryEngineFactory<{profileType}, {engineInterfaceName}>";

            source.AppendLine();
            source.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<{factoryInterface}>(services, serviceProvider => new {factoryImplementation}(serviceProvider, global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::TinyBlueWhale.EngineQuery.DependencyInjection.Configuration.EngineQueryRegistration>(serviceProvider), queryBuilder => new {engineImplementationName}(queryBuilder)));");
            source.AppendLine();
            source.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<{engineInterfaceName}>(services, serviceProvider => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{factoryInterface}>(serviceProvider).Create());");
        }
    }
}
