using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using TinyBlueWhale.EngineQuery.Generators.Discovery;
using TinyBlueWhale.EngineQuery.Generators.Models;
using TinyBlueWhale.EngineQuery.Generators.Rendering;
using TinyBlueWhale.EngineQuery.Generators.Resolution;

namespace TinyBlueWhale.EngineQuery.Generators.Generation
{
    /// <summary>
    /// Generates manual root and composition query feature extensions for locally
    /// declared database provider profiles.
    /// </summary>
    internal static class ManualExtensionGenerator
    {
        private const string GeneratedExtensionsNamespace =
            "TinyBlueWhale.EngineQuery.Abstractions.Extensions";

        /// <summary>
        /// Generates manual root and composition feature extensions associated with
        /// locally declared provider profiles.
        /// </summary>
        internal static void Generate(SourceProductionContext context, GenerationModel model)
        {
            if (model.ProfileContract is null)
                return;

            foreach (var profileModel in model.Profiles.Where(static profileModel => profileModel.IsLocal))
            {
                context.CancellationToken.ThrowIfCancellationRequested();

                if (profileModel.RootSurfaces.Count == 0 && profileModel.CompositionSurfaces.Count == 0)
                    continue;

                var source = Generate(profileModel, model.ProfileContract);

                context.AddSource($"{CSharpSourceRenderer.GetExtensionClassName(profileModel.Profile)}.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        }

        /// <summary>
        /// Generates manual root and composition query feature extensions for the specified profile.
        /// </summary>
        private static string Generate(ProfileSurfaceModel model, INamedTypeSymbol profileContract)
        {
            var profileType = model.Profile.ToDisplayString(CSharpSourceRenderer.GeneratedTypeDisplayFormat);
            var extensionClassName = CSharpSourceRenderer.GetExtensionClassName(model.Profile);
            var rootMethods = GetManualSurfaceMethods(model.RootSurfaces, profileContract);
            var compositionMethods = GetCompositionSurfaceMethods(model.CompositionSurfaces, profileContract);
            var source = new StringBuilder();

            source.AppendLine("// <auto-generated />");
            source.AppendLine("#nullable enable");
            source.AppendLine();
            source.AppendLine($"namespace {GeneratedExtensionsNamespace}");
            source.AppendLine("{");
            source.AppendLine("    /// <summary>");
            source.AppendLine("    /// Provides generated query feature extensions for");
            source.AppendLine($"    /// <see cref=\"{profileType}\"/>.");
            source.AppendLine("    /// </summary>");
            source.AppendLine($"    public static class {extensionClassName}");
            source.AppendLine("    {");

            var hasPreviousMethod = false;

            foreach (var method in rootMethods)
            {
                if (hasPreviousMethod)
                    source.AppendLine();

                AppendManualExtension(source, model, method);
                hasPreviousMethod = true;
            }

            foreach (var surfaceMethod in compositionMethods)
            {
                if (hasPreviousMethod)
                    source.AppendLine();

                AppendCompositionExtension(source, model, surfaceMethod, profileContract);
                hasPreviousMethod = true;
            }

            source.AppendLine("    }");
            source.AppendLine("}");

            return source.ToString();
        }

        /// <summary>
        /// Appends a generated manual root query feature extension.
        /// </summary>
        private static void AppendManualExtension(StringBuilder source, ProfileSurfaceModel model, IMethodSymbol method)
        {
            var profileType = model.Profile.ToDisplayString(CSharpSourceRenderer.GeneratedTypeDisplayFormat);
            var genericParameters = CSharpSourceRenderer.BuildGenericParameterList(method);

            var returnType = FeatureSurfaceResolver.IsRootSurfaceReturn(method.ReturnType, model)
                ? $"global::TinyBlueWhale.EngineQuery.Abstractions.Interfaces.IQueryBuilder<{profileType}>"
                : method.ReturnType.ToDisplayString(CSharpSourceRenderer.GeneratedTypeDisplayFormat);

            var parameterDeclarations = method.Parameters.Select(CSharpSourceRenderer.BuildParameterDeclaration).ToList();

            parameterDeclarations.Insert(0, $"this global::TinyBlueWhale.EngineQuery.Abstractions.Interfaces.IQueryBuilder<{profileType}> queryBuilder");

            var parameters = string.Join(", ", parameterDeclarations);
            var arguments = string.Join(", ", method.Parameters.Select(CSharpSourceRenderer.BuildArgument));

            source.AppendLine("        /// <summary>");
            source.AppendLine($"        /// Provides the generated {method.Name} root query feature operation.");
            source.AppendLine("        /// </summary>");

            foreach (var typeParameter in method.TypeParameters)
            {
                source.AppendLine($"        /// <typeparam name=\"{typeParameter.Name}\">");
                source.AppendLine("        /// Generic type parameter associated with the feature operation.");
                source.AppendLine("        /// </typeparam>");
            }

            source.AppendLine("        /// <param name=\"queryBuilder\">");
            source.AppendLine("        /// Current root query builder instance.");
            source.AppendLine("        /// </param>");

            foreach (var parameter in method.Parameters)
            {
                source.AppendLine($"        /// <param name=\"{parameter.Name}\">");
                source.AppendLine("        /// Feature operation argument.");
                source.AppendLine("        /// </param>");
            }

            source.AppendLine("        /// <returns>");
            source.AppendLine("        /// Result produced by the root query feature operation.");
            source.AppendLine("        /// </returns>");
            source.AppendLine($"        public static {returnType} {method.Name}{genericParameters}({parameters})");

            CSharpSourceRenderer.AppendGenericConstraints(source, method, "            ");

            source.AppendLine("        {");
            source.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(queryBuilder);");

            if (method.ReturnsVoid)
                source.AppendLine($"            queryBuilder.{method.Name}{genericParameters}({arguments});");
            else
                source.AppendLine($"            return queryBuilder.{method.Name}{genericParameters}({arguments});");

            source.AppendLine("        }");
        }

        /// <summary>
        /// Gets root feature methods exposed by the resolved root surface set.
        /// </summary>
        private static IReadOnlyList<IMethodSymbol> GetManualSurfaceMethods(IReadOnlyList<INamedTypeSymbol> surfaces, INamedTypeSymbol profileContract)
        {
            var methods = new List<IMethodSymbol>();

            foreach (var surface in surfaces)
                AddSurfaceMethodsForManual(surface, profileContract, methods);

            return [.. methods
                .GroupBy(FeatureSurfaceResolver.BuildMethodIdentity, StringComparer.Ordinal)
                .Select(static group => group.First())
                .OrderBy(static method => method.Name, StringComparer.Ordinal)
                .ThenBy(static method => method.Arity)
                .ThenBy(static method => method.Parameters.Length)];
        }

        /// <summary>
        /// Adds methods declared by a root surface and inherited root feature surfaces.
        /// </summary>
        private static void AddSurfaceMethodsForManual(INamedTypeSymbol surface, INamedTypeSymbol profileContract, ICollection<IMethodSymbol> methods)
        {
            foreach (var method in FeatureSurfaceResolver.GetDeclaredSurfaceMethods(surface))
                methods.Add(method);

            foreach (var inheritedSurface in surface.Interfaces)
            {
                if (!FeatureSurfaceDiscovery.IsConstructedRootFeatureSurface(inheritedSurface, profileContract))
                    continue;

                AddSurfaceMethodsForManual(inheritedSurface, profileContract, methods);
            }
        }

        /// <summary>
        /// Gets composition feature methods exposed by compatible composition surfaces.
        /// </summary>
        private static IReadOnlyList<SurfaceMethodModel> GetCompositionSurfaceMethods(IReadOnlyList<INamedTypeSymbol> surfaces, INamedTypeSymbol profileContract)
        {
            var methods = new List<SurfaceMethodModel>();

            foreach (var surface in surfaces)
                AddCompositionSurfaceMethods(surface, profileContract, methods);

            return [.. methods
                .GroupBy(BuildCompositionMethodIdentity, StringComparer.Ordinal)
                .Select(static group => group.First())
                .OrderBy(static model => model.Method.Name, StringComparer.Ordinal)
                .ThenBy(static model => model.Method.Arity)
                .ThenBy(static model => model.Method.Parameters.Length)];
        }

        /// <summary>
        /// Adds methods declared by a composition surface and inherited feature surfaces.
        /// </summary>
        private static void AddCompositionSurfaceMethods(INamedTypeSymbol surface, INamedTypeSymbol profileContract, ICollection<SurfaceMethodModel> methods)
        {
            foreach (var method in FeatureSurfaceResolver.GetDeclaredSurfaceMethods(surface))
                methods.Add(new SurfaceMethodModel(surface, method));

            foreach (var inheritedSurface in surface.Interfaces)
            {
                if (FeatureSurfaceDiscovery.GetProfileTypeParameterIndex(inheritedSurface.OriginalDefinition, profileContract) < 0)
                    continue;

                AddCompositionSurfaceMethods(inheritedSurface.OriginalDefinition, profileContract, methods);
            }
        }

        /// <summary>
        /// Appends a generated profile-closed composition feature extension.
        /// </summary>
        private static void AppendCompositionExtension(StringBuilder source, ProfileSurfaceModel model, SurfaceMethodModel surfaceMethod, INamedTypeSymbol profileContract)
        {
            var surface = surfaceMethod.Surface.OriginalDefinition;
            var method = surfaceMethod.Method;
            var profileParameterIndex = FeatureSurfaceDiscovery.GetProfileTypeParameterIndex(surface, profileContract);

            if (profileParameterIndex < 0)
                return;

            var profileParameter = surface.TypeParameters[profileParameterIndex];
            var promotedSurfaceParameters = surface.TypeParameters.Where((_, index) => index != profileParameterIndex).ToList();
            var substitutions = new Dictionary<ITypeParameterSymbol, string>(SymbolEqualityComparer.Default);
            var profileType = model.Profile.ToDisplayString(CSharpSourceRenderer.GeneratedTypeDisplayFormat);

            substitutions[profileParameter] = profileType;

            foreach (var typeParameter in promotedSurfaceParameters)
                substitutions[typeParameter] = typeParameter.Name;

            foreach (var typeParameter in method.TypeParameters)
                substitutions[typeParameter] = typeParameter.Name;

            var genericTypeParameters = promotedSurfaceParameters
                .Select(static parameter => parameter.Name)
                .Concat(method.TypeParameters.Select(static parameter => parameter.Name))
                .ToList();

            var genericParameters = genericTypeParameters.Count == 0
                ? string.Empty
                : $"<{string.Join(", ", genericTypeParameters)}>";

            var queryCommandBuilder = FeatureSurfaceResolver.FindQueryCommandBuilderSurface(surface);

            if (queryCommandBuilder is null)
                return;

            var receiverType = CSharpSourceRenderer.RenderType(queryCommandBuilder, substitutions);
            var returnType = CSharpSourceRenderer.RenderType(method.ReturnType, substitutions);
            var parameterDeclarations = method.Parameters.Select(parameter => CSharpSourceRenderer.BuildParameterDeclaration(parameter, substitutions)).ToList();

            parameterDeclarations.Insert(0, $"this {receiverType} queryBuilder");

            var parameters = string.Join(", ", parameterDeclarations);
            var arguments = string.Join(", ", method.Parameters.Select(CSharpSourceRenderer.BuildArgument));
            var hookName = $"Apply{method.Name}";
            var hookGenericParameters = method.TypeParameters.Length == 0
                ? string.Empty
                : $"<{string.Join(", ", method.TypeParameters.Select(static parameter => parameter.Name))}>";

            source.AppendLine("        /// <summary>");
            source.AppendLine($"        /// Provides the generated {method.Name} composition feature operation.");
            source.AppendLine("        /// </summary>");

            foreach (var typeParameter in promotedSurfaceParameters)
            {
                source.AppendLine($"        /// <typeparam name=\"{typeParameter.Name}\">");
                source.AppendLine("        /// Generic type parameter associated with the current query composition.");
                source.AppendLine("        /// </typeparam>");
            }

            foreach (var typeParameter in method.TypeParameters)
            {
                source.AppendLine($"        /// <typeparam name=\"{typeParameter.Name}\">");
                source.AppendLine("        /// Generic type parameter associated with the feature operation.");
                source.AppendLine("        /// </typeparam>");
            }

            source.AppendLine("        /// <param name=\"queryBuilder\">");
            source.AppendLine("        /// Current query command builder instance.");
            source.AppendLine("        /// </param>");

            foreach (var parameter in method.Parameters)
            {
                source.AppendLine($"        /// <param name=\"{parameter.Name}\">");
                source.AppendLine("        /// Feature operation argument.");
                source.AppendLine("        /// </param>");
            }

            source.AppendLine("        /// <returns>");
            source.AppendLine("        /// Result produced by the composition feature operation.");
            source.AppendLine("        /// </returns>");
            source.AppendLine($"        public static {returnType} {method.Name}{genericParameters}({parameters})");

            CSharpSourceRenderer.AppendGenericConstraints(source, promotedSurfaceParameters, substitutions, "            ");
            CSharpSourceRenderer.AppendGenericConstraints(source, method.TypeParameters, substitutions, "            ");

            source.AppendLine("        {");
            source.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(queryBuilder);");

            foreach (var parameter in method.Parameters.Where(static parameter => parameter.Type.TypeKind == TypeKind.Delegate))
                source.AppendLine($"            global::System.ArgumentNullException.ThrowIfNull({CSharpSourceRenderer.EscapeIdentifier(parameter.Name)});");

            if (method.ReturnsVoid)
                source.AppendLine($"            queryBuilder.{hookName}{hookGenericParameters}({arguments});");
            else
                source.AppendLine($"            return queryBuilder.{hookName}{hookGenericParameters}({arguments});");

            source.AppendLine("        }");
        }

        /// <summary>
        /// Builds an identity used to de-duplicate composition extension methods.
        /// </summary>
        private static string BuildCompositionMethodIdentity(SurfaceMethodModel model)
        {
            return $"{model.Surface.OriginalDefinition.ToDisplayString(CSharpSourceRenderer.GeneratedTypeDisplayFormat)}::{FeatureSurfaceResolver.BuildMethodIdentity(model.Method)}";
        }
    }
}
