using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using TinyBlueWhale.EngineQuery.Generators.Discovery;
using TinyBlueWhale.EngineQuery.Generators.Models;
using TinyBlueWhale.EngineQuery.Generators.Rendering;
using TinyBlueWhale.EngineQuery.Generators.Resolution;

namespace TinyBlueWhale.EngineQuery.Generators.Generation
{
    /// <summary>
    /// Generates strongly typed query engine interfaces and implementations for
    /// discovered database provider profiles.
    /// </summary>
    internal static class QueryEngineGenerator
    {
        private const string QueryEngineInterface =
            "TinyBlueWhale.EngineQuery.DependencyInjection.Interfaces.IQueryEngine";

        private const string GeneratedNamespace =
            "TinyBlueWhale.EngineQuery.Generated";

        private const string GeneratedExtensionsNamespace =
            "TinyBlueWhale.EngineQuery.Abstractions.Extensions";

        /// <summary>
        /// Generates query engine surfaces for discovered provider profiles when the
        /// corresponding generated engine type is not already available to the compilation.
        /// </summary>
        internal static void Generate(SourceProductionContext context, GenerationModel model)
        {
            if (model.ProfileContract is null)
                return;

            foreach (var profileModel in model.Profiles)
            {
                context.CancellationToken.ThrowIfCancellationRequested();

                var engineName = CSharpSourceRenderer.GetEngineName(profileModel.Profile);
                var engineMetadataName = $"{GeneratedNamespace}.{engineName}";

                if (model.Compilation.GetTypeByMetadataName(engineMetadataName) is not null)
                    continue;

                var source = Generate(profileModel, model.ProfileContract);

                context.AddSource($"{engineName}.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        }

        /// <summary>
        /// Generates the query engine surface and implementation associated with a profile.
        /// </summary>
        private static string Generate(ProfileSurfaceModel model, INamedTypeSymbol profileContract)
        {
            var profileType = model.Profile.ToDisplayString(CSharpSourceRenderer.GeneratedTypeDisplayFormat);
            var engineName = CSharpSourceRenderer.GetEngineName(model.Profile);
            var engineInterfaceName = $"I{engineName}";
            var source = new StringBuilder();

            source.AppendLine("// <auto-generated />");
            source.AppendLine("#nullable enable");
            source.AppendLine();
            source.AppendLine($"namespace {GeneratedNamespace}");
            source.AppendLine("{");

            AppendEngineInterface(source, profileType, engineInterfaceName, model.RootSurfaces);

            source.AppendLine();

            AppendEngineImplementation(source, model, profileContract, profileType, engineName, engineInterfaceName);

            source.AppendLine("}");

            return source.ToString();
        }

        /// <summary>
        /// Appends the generated public query engine interface associated with a provider profile.
        /// </summary>
        private static void AppendEngineInterface(StringBuilder source, string profileType, string engineInterfaceName, IReadOnlyList<INamedTypeSymbol> featureSurfaces)
        {
            var surfaces = new List<string>
            {
                $"global::{QueryEngineInterface}<{profileType}>"
            };

            surfaces.AddRange(featureSurfaces.Select(surface => surface.ToDisplayString(CSharpSourceRenderer.GeneratedTypeDisplayFormat)));

            source.AppendLine("    /// <summary>");
            source.AppendLine("    /// Represents the generated query engine surface associated with");
            source.AppendLine($"    /// <see cref=\"{profileType}\"/>.");
            source.AppendLine("    /// </summary>");
            source.AppendLine($"    public interface {engineInterfaceName} :");

            for (var index = 0; index < surfaces.Count; index++)
            {
                source.Append("        ");
                source.Append(surfaces[index]);

                if (index < surfaces.Count - 1)
                    source.Append(',');

                source.AppendLine();
            }

            source.AppendLine("    {");
            source.AppendLine("    }");
        }

        /// <summary>
        /// Appends the generated query engine implementation associated with a provider profile.
        /// </summary>
        private static void AppendEngineImplementation(StringBuilder source, ProfileSurfaceModel model, INamedTypeSymbol profileContract, string profileType, string engineName, string engineInterfaceName)
        {
            source.AppendLine("    /// <summary>");
            source.AppendLine("    /// Provides the generated query engine implementation associated with");
            source.AppendLine($"    /// <see cref=\"{profileType}\"/>.");
            source.AppendLine("    /// </summary>");
            source.AppendLine($"    internal sealed class {engineName}(global::TinyBlueWhale.EngineQuery.Core.QueryBuilding.QueryBuilder<{profileType}> queryBuilder) :");
            source.AppendLine($"        global::TinyBlueWhale.EngineQuery.DependencyInjection.QueryEngine<{profileType}>(queryBuilder),");
            source.AppendLine($"        {engineInterfaceName}");
            source.AppendLine("    {");

            var surfaceMethods = GetDependencyInjectionSurfaceMethods(model.RootSurfaces, profileContract);

            for (var index = 0; index < surfaceMethods.Count; index++)
            {
                AppendDependencyInjectionSurfaceMethod(source, model, surfaceMethods[index]);

                if (index < surfaceMethods.Count - 1)
                    source.AppendLine();
            }

            source.AppendLine("    }");
        }

        /// <summary>
        /// Gets root surface methods requiring explicit dependency injection forwarding implementations.
        /// </summary>
        private static IReadOnlyList<SurfaceMethodModel> GetDependencyInjectionSurfaceMethods(IReadOnlyList<INamedTypeSymbol> surfaces, INamedTypeSymbol profileContract)
        {
            var methods = new List<SurfaceMethodModel>();

            foreach (var surface in surfaces)
                AddDependencyInjectionSurfaceMethods(surface, profileContract, methods);

            return [.. methods
                .GroupBy(BuildDependencyInjectionMethodIdentity, StringComparer.Ordinal)
                .Select(static group => group.First())
                .OrderBy(static method => method.Surface.ToDisplayString(), StringComparer.Ordinal)
                .ThenBy(static method => method.Method.Name, StringComparer.Ordinal)
                .ThenBy(static method => method.Method.Arity)
                .ThenBy(static method => method.Method.Parameters.Length)];
        }

        /// <summary>
        /// Adds methods declared by a root feature surface and inherited root contracts.
        /// </summary>
        private static void AddDependencyInjectionSurfaceMethods(INamedTypeSymbol surface, INamedTypeSymbol profileContract, ICollection<SurfaceMethodModel> methods)
        {
            foreach (var method in FeatureSurfaceResolver.GetDeclaredSurfaceMethods(surface))
                methods.Add(new SurfaceMethodModel(surface, method));

            foreach (var inheritedSurface in surface.Interfaces)
            {
                if (!FeatureSurfaceDiscovery.IsConstructedRootFeatureSurface(inheritedSurface, profileContract))
                    continue;

                AddDependencyInjectionSurfaceMethods(inheritedSurface, profileContract, methods);
            }
        }

        /// <summary>
        /// Appends an explicit root feature implementation to a generated query engine.
        /// </summary>
        private static void AppendDependencyInjectionSurfaceMethod(StringBuilder source, ProfileSurfaceModel model, SurfaceMethodModel surfaceMethod)
        {
            var surfaceType = surfaceMethod.Surface.ToDisplayString(CSharpSourceRenderer.GeneratedTypeDisplayFormat);
            var method = surfaceMethod.Method;
            var returnType = method.ReturnType.ToDisplayString(CSharpSourceRenderer.GeneratedTypeDisplayFormat);
            var genericParameters = CSharpSourceRenderer.BuildGenericParameterList(method);
            var parameters = string.Join(", ", method.Parameters.Select(CSharpSourceRenderer.BuildRequiredParameterDeclaration));
            var arguments = string.Join(", ", method.Parameters.Select(CSharpSourceRenderer.BuildArgument));
            var extensionType = $"global::{GeneratedExtensionsNamespace}.{CSharpSourceRenderer.GetExtensionClassName(model.Profile)}";

            source.AppendLine("        /// <inheritdoc />");
            source.AppendLine($"        {returnType} {surfaceType}.{method.Name}{genericParameters}({parameters})");

            CSharpSourceRenderer.AppendGenericConstraints(source, method, "            ");

            source.AppendLine("        {");

            if (FeatureSurfaceResolver.IsRootSurfaceReturn(method.ReturnType, model))
            {
                source.AppendLine($"            {extensionType}.{method.Name}{genericParameters}(_innerQueryBuilder{CSharpSourceRenderer.BuildForwardedArgumentSuffix(arguments)});");
                source.AppendLine("            return this;");
            }
            else if (method.ReturnsVoid)
            {
                source.AppendLine($"            {extensionType}.{method.Name}{genericParameters}(_innerQueryBuilder{CSharpSourceRenderer.BuildForwardedArgumentSuffix(arguments)});");
            }
            else
            {
                source.AppendLine($"            return {extensionType}.{method.Name}{genericParameters}(_innerQueryBuilder{CSharpSourceRenderer.BuildForwardedArgumentSuffix(arguments)});");
            }

            source.AppendLine("        }");
        }

        /// <summary>
        /// Builds an identity used to de-duplicate dependency injection surface implementations.
        /// </summary>
        private static string BuildDependencyInjectionMethodIdentity(SurfaceMethodModel model)
        {
            return $"{model.Surface.ToDisplayString(CSharpSourceRenderer.GeneratedTypeDisplayFormat)}::{FeatureSurfaceResolver.BuildMethodIdentity(model.Method)}";
        }
    }
}
