<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>TinyBlueWhale.EngineQuery.Abstractions</PackageId>
    <Description>Shared contracts and models for EngineQuery SQL generation.</Description>
    <PackageTags>dotnet;sql;query-builder;abstractions;contracts;enginequery</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />

    <InternalsVisibleTo Include="TinyBlueWhale.EngineQuery.Core" />
    <InternalsVisibleTo Include="TinyBlueWhale.EngineQuery.SqlServer" />
    <InternalsVisibleTo Include="TinyBlueWhale.EngineQuery.PostgreSql" />
    <InternalsVisibleTo Include="TinyBlueWhale.EngineQuery.MySql" />
  </ItemGroup>

</Project>