using TinyBlueWhale.EngineQuery.Core.QueryDefinitions;
using TinyBlueWhale.EngineQuery.Sql.Clauses.Pagination;
using TinyBlueWhale.EngineQuery.Sql.Compilation;

namespace TinyBlueWhale.EngineQuery.SqlServer.Clauses.Strategies.Pagination
{
    /// <summary>
    /// Provides SQL Server 2012 and later pagination behavior.
    /// </summary>
    /// <remarks>
    /// SQL Server OFFSET/FETCH pagination requires an ORDER BY clause.
    /// The actual pagination syntax is generated by the configured SQL Server dialect.
    /// </remarks>
    public sealed class SqlServer2012PaginationStrategy : PaginationStrategy
    {
        /// <summary>
        /// Builds the SQL Server pagination clause for the specified query definition.
        /// </summary>
        /// <param name="queryDefinition">
        /// Query definition containing pagination and ordering metadata.
        /// </param>
        /// <param name="context">
        /// Current SQL compilation context.
        /// </param>
        /// <returns>
        /// SQL Server OFFSET/FETCH pagination clause.
        /// </returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="queryDefinition"/> or
        /// <paramref name="context"/> is null.
        /// </exception>
        /// <exception cref="InvalidOperationException">
        /// Thrown when pagination is requested without an ORDER BY clause.
        /// </exception>
        public override string Build(CompiledQueryDefinition queryDefinition, QueryCompilationContext context)
        {
            ArgumentNullException.ThrowIfNull(queryDefinition);
            ArgumentNullException.ThrowIfNull(context);

            if (queryDefinition.OrderingDefinitions.Count == 0)
                throw new InvalidOperationException("SQL Server pagination requires at least one ORDER BY clause.");

            return base.Build(queryDefinition, context);
        }
    }
}
