using TinyBlueWhale.EngineQuery.Core.QueryDefinitions;
using TinyBlueWhale.EngineQuery.Sql.Clauses.Pagination;
using TinyBlueWhale.EngineQuery.Sql.Compilation;

namespace TinyBlueWhale.EngineQuery.SqlServer.Clauses.Strategies.Pagination
{
    /// <summary>
    /// Provides SQL Server 2012 and later pagination behavior.
    /// </summary>
    /// <remarks>
    /// SQL Server OFFSET/FETCH pagination requires an ORDER BY clause.
    /// The actual pagination syntax is generated by the configured SQL Server dialect.
    /// </remarks>
    public sealed class SqlServer2012PaginationStrategy : PaginationStrategy
    {
        /// <inheritdoc />
        public override string Build(CompiledQueryDefinition queryDefinition, QueryCompilationContext context)
        {
            ArgumentNullException.ThrowIfNull(queryDefinition);
            ArgumentNullException.ThrowIfNull(context);

            if (queryDefinition.OrderingDefinitions.Count == 0)
                throw new InvalidOperationException("SQL Server pagination requires at least one ORDER BY clause.");

            return base.Build(queryDefinition, context);
        }
    }
}
