<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>TinyBlueWhale.EngineQuery.MySql</PackageId>
    <Description>MySQL provider for EngineQuery deterministic SQL generation.</Description>
    <PackageTags>dotnet;sql;query-builder;mysql;dapper;cqrs;enginequery</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TinyBlueWhale.EngineQuery.Core\TinyBlueWhale.EngineQuery.Core.csproj" />
    <ProjectReference Include="..\TinyBlueWhale.EngineQuery.Sql\TinyBlueWhale.EngineQuery.Sql.csproj" />

    <InternalsVisibleTo Include="TinyBlueWhale.EngineQuery.DependencyInjection" />

    <ProjectReference Include="..\TinyBlueWhale.EngineQuery.Generators\TinyBlueWhale.EngineQuery.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>