using System.Text.RegularExpressions;
using TinyBlueWhale.EngineQuery.Abstractions.Models;
using TinyBlueWhale.EngineQuery.Core.Parameters;

namespace TinyBlueWhale.EngineQuery.Sql.Helpers
{

    /// <summary>
    /// Rewrites SQL parameter names from a nested query into a parent parameter collection.
    /// </summary>
    /// <remarks>
    /// This helper prevents parameter name collisions when derived tables, CTEs, EXISTS,
    /// IN subqueries, APPLY clauses or set operations are merged into a parent SQL command.
    /// </remarks>
    public sealed class SqlParameterRewriter
    {
        /// <summary>
        /// Rewrites all parameters from a source query into the target parameter collection.
        /// </summary>
        /// <param name="commandText">
        /// SQL command text that contains source parameter names.
        /// </param>
        /// <param name="sourceParameters">
        /// Parameters generated by the nested query.
        /// </param>
        /// <param name="targetParameters">
        /// Parent parameter collection that will receive rewritten parameters.
        /// </param>
        /// <returns>
        /// SQL command text with rewritten parameter names.
        /// </returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="sourceParameters"/> or <paramref name="targetParameters"/> is <see langword="null"/>.
        /// </exception>
        public static string Rewrite(string commandText, IEnumerable<QuerySqlParameter> sourceParameters, QueryParameterCollection targetParameters)
        {
            ArgumentNullException.ThrowIfNull(sourceParameters);
            ArgumentNullException.ThrowIfNull(targetParameters);

            foreach (var parameter in sourceParameters.OrderByDescending(parameter => parameter.Name.Length))
            {
                var rewrittenParameter = targetParameters.AddRewritten(parameter);

                commandText = ReplaceParameterName(
                    commandText,
                    parameter.Name,
                    rewrittenParameter.Name);
            }

            return commandText;
        }

        /// <summary>
        /// Replaces a SQL parameter name without matching partial parameter names.
        /// </summary>
        /// <param name="commandText">
        /// SQL command text to update.
        /// </param>
        /// <param name="oldName">
        /// Existing parameter name.
        /// </param>
        /// <param name="newName">
        /// Replacement parameter name.
        /// </param>
        /// <returns>
        /// SQL command text with the parameter name replaced.
        /// </returns>
        private static string ReplaceParameterName(string commandText, string oldName, string newName)
        {
            return Regex.Replace(
                commandText,
                $@"(?<![\w@]){Regex.Escape(oldName)}(?!\w)",
                newName,
                RegexOptions.CultureInvariant);
        }
    }
}
