using System.Text.RegularExpressions;
using TinyBlueWhale.EngineQuery.Abstractions.Models;
using TinyBlueWhale.EngineQuery.Core.Parameters;

namespace TinyBlueWhale.EngineQuery.Sql.Helpers
{

    /// <summary>
    /// Rewrites SQL parameter names from a nested query into a parent parameter collection.
    /// </summary>
    /// <remarks>
    /// This helper prevents parameter name collisions when derived tables, CTEs, EXISTS,
    /// IN subqueries, APPLY clauses or set operations are merged into a parent SQL command.
    /// </remarks>
    public sealed class SqlParameterRewriter
    {
        /// <summary>
        /// Rewrites all parameters from a source query into the target parameter collection.
        /// </summary>
        /// <param name="commandText">
        /// SQL command text that contains source parameter names.
        /// </param>
        /// <param name="sourceParameters">
        /// Parameters generated by the nested query.
        /// </param>
        /// <param name="targetParameters">
        /// Parent parameter collection that will receive rewritten parameters.
        /// </param>
        /// <returns>
        /// SQL command text with rewritten parameter names.
        /// </returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="sourceParameters"/> or <paramref name="targetParameters"/> is <see langword="null"/>.
        /// </exception>
        public static string Rewrite(string commandText, IEnumerable<QuerySqlParameter> sourceParameters, QueryParameterCollection targetParameters)
        {
            ArgumentNullException.ThrowIfNull(sourceParameters);
            ArgumentNullException.ThrowIfNull(targetParameters);

            Dictionary<string, string> replacements = new(StringComparer.Ordinal);

            foreach (QuerySqlParameter parameter in sourceParameters)
            {
                QuerySqlParameter rewrittenParameter = targetParameters.AddRewritten(parameter);

                replacements.Add(parameter.Name, rewrittenParameter.Name);
            }

            if (replacements.Count == 0)
                return commandText;

            string parameterPattern = string.Join("|", replacements.Keys.OrderByDescending(name => name.Length).Select(Regex.Escape));

            return Regex.Replace(commandText,
                $@"(?<![\w@])(?:{parameterPattern})(?!\w)",
                match => replacements[match.Value],
                RegexOptions.CultureInvariant);

        }
    }
}
