using TinyBlueWhale.EngineQuery.Abstractions.Models;
using TinyBlueWhale.EngineQuery.Core.Interfaces;
using System.Linq.Expressions;


namespace TinyBlueWhale.EngineQuery.Sql.ExpressionsParsing
{
    /// <summary>
    /// Parses computed expression trees into SQL expressions.
    /// </summary>
    public sealed class SqlComputedExpressionParser(ISqlDatabaseDialect databaseDialect, List<QuerySqlParameter> sqlParameters, IReadOnlyDictionary<string, string>? columnMappings, string? sourceAlias)
    {
        private readonly ISqlDatabaseDialect _databaseDialect = databaseDialect;
        private readonly List<QuerySqlParameter> _sqlParameters = sqlParameters;
        private readonly IReadOnlyDictionary<string, string>? _columnMappings = columnMappings;
        private readonly string? _sourceAlias = sourceAlias;

        /// <summary>
        /// Parses the specified expression into a SQL computed expression.
        /// </summary>
        public string Parse(Expression expression)
        {
            return ParseExpression(UnwrapConvertExpression(expression));
        }

        // Parses supported computed SQL expressions.
        private string ParseExpression(Expression expression)
        {
            return expression switch
            {
                BinaryExpression binaryExpression => ParseBinaryExpression(binaryExpression),
                MemberExpression memberExpression => ParseMemberExpression(memberExpression),
                ConstantExpression constantExpression => AddSqlParameter(constantExpression.Value),
                _ => throw new NotSupportedException($"Computed expression '{expression}' is not supported.")
            };
        }

        // Parses binary expressions such as addition, subtraction, multiplication and division.
        private string ParseBinaryExpression(BinaryExpression binaryExpression)
        {
            var left = ParseExpression(UnwrapConvertExpression(binaryExpression.Left));
            var right = ParseExpression(UnwrapConvertExpression(binaryExpression.Right));
            var sqlOperator = ResolveSqlOperator(binaryExpression.NodeType);

            return $"({left} {sqlOperator} {right})";
        }

        // Parses member access expressions as SQL column references.
        private string ParseMemberExpression(MemberExpression memberExpression)
        {
            if (memberExpression.Expression is not ParameterExpression)
                return AddSqlParameter(Expression.Lambda(memberExpression).Compile().DynamicInvoke());

            var propertyName = memberExpression.Member.Name;
            var columnName = ResolveMappedColumnName(propertyName);

            return string.IsNullOrWhiteSpace(_sourceAlias)
                ? _databaseDialect.EscapeIdentifier(columnName)
                : _databaseDialect.BuildQualifiedIdentifier(_sourceAlias, columnName);
        }

        // Resolves the SQL operator associated with the expression type.
        private static string ResolveSqlOperator(ExpressionType expressionType)
        {
            return expressionType switch
            {
                ExpressionType.Add => "+",
                ExpressionType.Subtract => "-",
                ExpressionType.Multiply => "*",
                ExpressionType.Divide => "/",
                ExpressionType.Equal => "=",
                ExpressionType.NotEqual => "<>",
                ExpressionType.GreaterThan => ">",
                ExpressionType.GreaterThanOrEqual => ">=",
                ExpressionType.LessThan => "<",
                ExpressionType.LessThanOrEqual => "<=",
                _ => throw new NotSupportedException($"Computed expression operator '{expressionType}' is not supported.")
            };
        }

        // Resolves mapped column names.
        private string ResolveMappedColumnName(string propertyName)
        {
            if (_columnMappings is null)
                return propertyName;

            return _columnMappings.TryGetValue(propertyName, out var columnName)
                ? columnName
                : propertyName;
        }

        // Adds a SQL parameter and returns the generated parameter name.
        private string AddSqlParameter(object? value)
        {
            var parameterName = $"@p{_sqlParameters.Count}";

            _sqlParameters.Add(
                new QuerySqlParameter
                {
                    Name = parameterName,
                    Value = value
                });

            return parameterName;
        }

        // Removes boxing conversions generated by object-returning expression selectors.
        private static Expression UnwrapConvertExpression(Expression expression)
        {
            return expression is UnaryExpression unaryExpression &&
                   unaryExpression.NodeType == ExpressionType.Convert
                ? unaryExpression.Operand
                : expression;
        }
    }
}
