<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>TinyBlueWhale.EngineQuery.PostgreSql</PackageId>
    <Description>PostgreSQL provider for EngineQuery deterministic SQL generation.</Description>
    <PackageTags>dotnet;sql;query-builder;postgresql;postgres;dapper;cqrs;enginequery</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TinyBlueWhale.EngineQuery.Core\TinyBlueWhale.EngineQuery.Core.csproj" />
    <ProjectReference Include="..\TinyBlueWhale.EngineQuery.Sql\TinyBlueWhale.EngineQuery.Sql.csproj" />

    <InternalsVisibleTo Include="TinyBlueWhale.EngineQuery.DependencyInjection" />

  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>